### ISSUE TITLE
Repository link is broken

### ISSUE THREAD

**Issue by rparrett** [oscrim/bevy_shape_draw#2]
Hello. Stumbled upon your crate while browsing lib.rs and noticed that the link back to the repository was broken.

Looks like there's an extra `https://` here:

https://github.com/oscrim/bevy_shape_draw/blob/42d6253aa7e1912130f68d60310e9dcd2f240090/Cargo.toml#L11

**Comment by oscrim** [comment]
Oh I completely missed that, thank you very much! Ill fix it right away
